name: geo-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - rasterio
  - geopandas
  - xarray
  - pandas
  - numpy
  - scikit-image
  - scipy
  - matplotlib
  - shapely
  - requests
  - tqdm
  - pip
  - pip:
    - pystac-client
    - ipykernel
